### ISSUE TITLE
Could not install the extension on .Net 5 project

### ISSUE THREAD

**Issue by rahul7720** [OData/Extensions#44]
Error	NU1107	Version conflict detected for Microsoft.Extensions.DependencyInjection. Install/reference Microsoft.Extensions.DependencyInjection 5.0.0-preview.7.20364.11 directly to project Test.WebClient to resolve this issue. 
 Test.WebClient -> Test.DataService -> Test.Entity -> Microsoft.AspNetCore.Identity.EntityFrameworkCore 5.0.0-preview.7.20365.19 -> Microsoft.EntityFrameworkCore.Relational 5.0.0-preview.7.20365.15 -> Microsoft.EntityFrameworkCore 5.0.0-preview.7.20365.15 -> Microsoft.Extensions.DependencyInjection (>= 5.0.0-preview.7.20364.11) 
 Test.WebClient -> Microsoft.OData.Extensions.Client 1.0.2 -> Microsoft.Extensions.DependencyInjection (>= 2.1.0 && < 4.0.0).	Test.WebClient	D:\Projects\Test.WebClient.csproj	1

**Comment by xuzhg** [comment]
@groovyfeng

**Comment by rahul7720** [comment]
This issue is resolved after upgrading to 5.0.0-preview.8 and by installing relevent Microsoft.Extensions.DependencyInjection dependency nuget packages
